### PR TITLE
Migrate build to hatch

### PR DESCRIPTION
**Pull request by fsouza**

### CODE REVIEW

**Comment by ofek** [comment]
Hello! Was there an issue?

**Comment by fsouza** [comment]
> Hello! Was there an issue?

No, did you run into any issues with this change?

**Comment by ofek** [comment]
No I just saw this was closed but didn't know why

**Comment by fsouza** [comment]
> No I just saw this was closed but didn't know why

Oh, I see. The change is merged, but I made a mistake when merging and GitHub shows the PR as closed instead of merged.

**Comment by ofek** [comment]
Ah okay, thanks!

**Pull request closed without merging**
