### PR TITLE
Add entry_points autoflake = autoflake:main to setup.cfg

### LINKED ISSUE #127: v1.5 release missing entry point?
Just tried out the [v1.5 release](https://github.com/PyCQA/autoflake/releases/tag/v1.5.0) but it's giving me command not found error

```sh
pip install autoflake==1.5.0
autoflake **/*.py
>>> zsh: command not found: autoflake
```

I see all the setup config moved to [`setup.cfg`](https://github.com/PyCQA/autoflake/blob/711d076474/setup.cfg) but it looks like the `[options.entry_points]` got lost somewhere on the way.

### PR DESCRIPTION
**Pull request by janosh**
Closes #127.

### CODE REVIEW

**Review by fsouza — APPROVED** [review]
Thanks for the quickfix and apologies for such a silly mistake. I reviewed and that was indeed the only thing I missed when migrating to setup.cfg.

I'll push a new release after merging.

**Comment by janosh** [comment]
It happens. 😄

**Comment by fsouza** [comment]
1.5.1 is out now. Again, thanks for the quick report and fix!

**Comment by janosh** [comment]
Works like a charm.

**Pull request merged**
